name: deploy demo app

on:
  push:
    branches:
      - master

env:
  OCI_CLI_USER: ${{ocid1.user.oc1..aaaaaaaadv5p7m6j4aonkiropffukudkqpualb6xnykwfm3yg3njgaubwpla}}
  OCI_CLI_TENANCY: ${{ocid1.tenancy.oc1..aaaaaaaa2wmldo5wroprhbx7egixtj4c2fmgod2ngbhth6igtr5wirkmw7aa}}
  OCI_CLI_FINGERPRINT: ${{ad:6f:18:4a:54:8c:e5:b7:cc:d0:6f:5a:ce:b1:55:9a}}
  OCI_CLI_KEY_CONTENT: ${{-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Zwnu+0hvsEdS1CM/a4ua8gLUn163tB6cDu9+7HaaCr77Mj0kyuv8EvWSdproPMbLVMByCvW88zQduJBdBJBz48h+9PYrPLbjmf7d8+9Ys9UpKja5KIGaOXgEPlLxGdq3rmHWJDOBLeOKd8VUCT8JS2GbOTkxlj8w3qtAM44VUSol1KL957TqxvHxBz0e1CKOhtK349IG8G5AYJmecpCitvPWVmgT4TKkwJPysvxaU6wRHVIPABCHUyyvURWeuLl0yzTQVGTW/y6YV7tf6Mk3o1HjxwkQDG4tTBTEn7o7yqhPpNEZRXHnH1JjmTyC7V2ckXkyw4A/V66OCIJTso8yQIDAQAB-----END PUBLIC KEY-----}}
  OCI_CLI_REGION: ${{sa-saopaulo-1}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get Access to OCIR
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.0
        with:
          name: ${{ grk77igdkclx }}
          compartment: ${{ocid1.compartment.oc1..aaaaaaaarpxdqrhkvufdxwavorfm4hg7vo3ciyolnlodbqbadpwbsrpeb3qa}}
      
      - name: Log Into OCIR
        uses: oracle-actions/login-ocir@v1.0
        id: login-ocir
        with:
          auth_token: ${{c8t0ZRml)_3A-TkfIl1n}}
      
      - name: Docker Build
        id: docker-build
        run: |
          docker build -t ${{ grk77igdkclx }}:${{ github.sha }} .
      
      - name: Docker Push
        id: docker-push
        run: |
          docker push ${{ grk77igdkclx }}:${{ github.sha }}
      
      - name: Upload Chart 
        uses: actions/upload-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download Chart
        uses: actions/download-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.0
        id: kubectl-oke-action
        with:
          cluster: ${{ secrets.ocid1.cluster.oc1.sa-saopaulo-1.aaaaaaaaqkuocdurlirfhnc7ycsrxwffdppyv6hazbww5sb56cicte5dvahq }}
      
      - name: Helm Deploy
        id: helm-deploy
        run: |
          helm upgrade \
            demo chart/ \
            --install --wait \
            --values chart/demo.yaml \
            --set image.tag=${{ github.sha }} \
            --namespace demo
